---
global:
  resolve_timeout: 1m
  # Здесь будет webhook для Slack
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 30m
  receiver: "slack"
  routes:
    - receiver: "slack"
      group_wait: 10s
      match_re:
        severity: critical|warning
      continue: true

receivers:
  - name: "slack"
    slack_configs:
      - send_resolved: true
        # Имя канала нотификаций для вашей когорты
        channel: '#dvs_06_notifications'
        text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"