variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - k8s-pipeline

kubernetes:
  stage: k8s-pipeline
  trigger:
    include:
      - "/kubernetes/.gitlab-ci.yml"
    strategy: depend
  # only:
  #   changes:
  #     - kubernetes/**/*