# Секрет, необходимый, чтобы соединяться с Vault и получать креды для БД:
---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
data:
  vault_token: bXlyb290
type: Opaque

# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOnsidXNlcm5hbWUiOiJhLmxpc2l0c2luIiwicGFzc3dvcmQiOiJcdTAwM2VlbjUhRmE2IiwiYXV0aCI6IllTNXNhWE5wZEhOcGJqbytaVzQxSVVaaE5nPT0ifX19
type: kubernetes.io/dockerconfigjson