---
# tasks file for backend
- name: refresh cache
  apt: update_cache=true
  when: ansible_os_family == 'Debian'
  changed_when: false
  become: yes

- name: install java
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - openjdk-16-jdk
      - python3-lxml
  become: yes

- name: add user
  user:
    name: "jarservice"
    shell: /bin/bash
    createhome: no
  become: yes

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: jarservice
    group: jarservice
  loop:
    - /opt/sausage-store/backend/lib
    - /opt/log
  become: yes

- name: download artifact 
  maven_artifact:
    dest: "/opt/sausage-store/backend/lib/sausage-store.jar"
    repository_url: "https://nexus.praktikum-services.ru/repository/sausage-store-lisitsin-aleksandr-backend/"
    group_id: "com.yandex.practicum.devops"
    artifact_id: "sausage-store"
    version: "1.0.103565"
    username: "{{ nexus_login }}"
    password: "{{ nexus_password }}"
    owner: jarservice
    group: jarservice
  become: yes

- name: unit service creation
  template:
    src: sausage-store-backend.service.j2
    dest: /etc/systemd/system/sausage-store-backend.service
  become: yes

- name: daemon reload
  systemd:
    daemon_reload: yes
  become: yes

- name: run application
  service:
    name: sausage-store-backend
    state: restarted
  become: yes
