variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - deploy

include:
  - project: "templates/ci"
    file: "DockerInDockerTemplate.yml"

deploy-k8s:
  stage: deploy
  image: alpine:3.15.0
  when: manual
  
  before_script:
    - apk add openssh-client bash
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  
  script:
    - ssh ${DEV_USER}@${DEV_HOST} "mkdir -p ./k8s-deploy"
    - ssh ${DEV_USER}@${DEV_HOST} "rm -rf ./k8s-deploy/*"
    - scp -rp ./kubernetes/backend ${DEV_USER}@${DEV_HOST}:/home/student/k8s-deploy
    - scp -rp ./kubernetes/backend-report ${DEV_USER}@${DEV_HOST}:/home/student/k8s-deploy
    - scp -rp ./kubernetes/frontend ${DEV_USER}@${DEV_HOST}:/home/student/k8s-deploy
    - ssh ${DEV_USER}@${DEV_HOST} "export "K8SCONFIG=${KUBECONFIG}"";
      /bin/bash -s " < ./kubernetes/deploy-k8s.sh

  environment:
    name: lisitsin-aleksandr-06.k8s.praktikum-services.tech
    url: https://lisitsin-aleksandr-06.k8s.praktikum-services.tech